production:
  adapter: mysql
  encoding: utf8
  database: owm_db
  username: owm_db_user
  password: ********
  host: 127.0.0.1
  port: 3306

development:
adapter: mysql
  encoding: utf8
  database: owm_db
  username: owm_db_user
  password: ******
  host: 127.0.0.1
  port: 3306

test:
adapter: mysql
  encoding: utf8
  database: owm_db
  username: owm_db_user
  password: ******
  host: 127.0.0.1
  port: 3306
