production:
  adapter: mysql2
  encoding: utf8
  database: owums_db
  pool: 5
  username: owums_db_user
  password: owums_db_user_password
  host: localhost


development:
  adapter: mysql2
  encoding: utf8
  database: owums_db
  pool: 5
  username: owums_db_user
  password: owums_db_user_password
  host: localhost


test:
  adapter: mysql2
  encoding: utf8
  database: owums_db
  pool: 5
  username: owums_db_user
  password: owums_db_user_password
  host: localhost
